# Local chat radius
local-chat-radius: 100

# Prefix for global chat (By default and most popular - "!")
global-chat-prefix: "!"

# log messages to console (by default on true)
enable-console-logging: true

# Messages examples. Placeholders: {player} - player-nickname, {message} - message, {prefix} - prefix from LuckyPerms
# Example for global message.
global-chat-format: "<dark_gray>[<green>G</green>]</dark_gray> {prefix} <gold>{player}</gold> <gray>>>></gray> <white>{message}</white>"
# Example for local message.
local-chat-format: "<dark_gray>[<blue>L</blue>]</dark_gray> {prefix} <gold>{player}</gold> <gray>>>></gray> <white>{message}</white>"
