# Local chat radius
local-chat-radius: 100

# Prefix for global chat
global-chat-prefix: "!"

# Example for global message. {player} - player-nickname, {message} - message
global-chat-format: "<dark_gray>[<red>G</red>]</dark_gray> <gold>{player}</gold> <gray>>>></gray> <white>{message}</white>"

# Example for local message. {player} - player-nickname, {message} - message
local-chat-format: "<dark_gray>[<green>L</green>]</dark_gray> <gold>{player}</gold> <gray>>>></gray> <white>{message}</white>"

# log messages to console (by default on true)
enable-console-logging: true